/** Every learner-facing string. Product vocabulary follows CLAUDE.md. */
export const COPY = {
  idleTitle: "Hodey",
  startHode: "Start a Hode",
  begin: "Begin",
  askHodey: "Ask Hodey",
  looking: "Hodey is looking at this screen…",
  needHint: "Need a hint?",
  hint: "Hint",
  explain: "Explain",
  letMeTry: "Let me try",
  pointAndAsk: "Point & Ask",
  pause: "Pause",
  resume: "Resume",
  end: "End Hode",
  retry: "Try again",
  gotIt: "Got it",
  cancel: "Cancel",
  mute: "Mute voice",
  unmute: "Unmute voice",
  paused: "Paused",
  hodeComplete: "Hode complete",
  skillLearned: "Skill learned ✓",
  goalPrompt: "What do you want to learn?",
  goalPlaceholder: "e.g. make a pivot table in Excel",
  annotateTitle: "Mark the spot, then ask",
  annotateDetail: "Drag a box · Shift-draw to circle · Esc to cancel",
  composerPlaceholder: "Ask about this area…",
  composerHint: "Enter to ask · Esc to cancel",
  whatIsThis: "What is this?",
  howDoIUse: "How do I use this?",
  focusHere: "Focus here",
  somethingWrong: "Hodey hit a problem",
  local: "Local",
  enhanced: "Cloud",
  cloud: "Cloud",
  cloudMenu: "Local or cloud",
  cloudMode: "Where Hodey thinks and speaks",
  localModeHint: "Everything runs on this PC.",
  cloudModeHint: "Cloud services you have keys for help out. Your screen and voice never leave this PC.",
  cloudNeedsKey: "Add a Gemini, ElevenLabs or Backboard key in Settings › Cloud to use the cloud.",
  serviceOff: "Off",
  geminiReasoning: "Reasoning · Gemini",
  elevenlabsVoiceModel: "Voice · ElevenLabs model",
  elevenlabsVoice: "ElevenLabs voice",
  backboardMemory: "Memory · Backboard",
  memoryOff: "Off",
  memoryRecall: "Recall only",
  memoryRecallSave: "Recall and save",
  cloudMenuLoading: "Reading your cloud choices…",
  cloudMenuFailed: "Couldn't read your cloud choices",
  cloudPrivacy: "Sensitive apps always stay local.",
  localTitle: "Everything runs on this PC",
  enhancedTitle: "A cloud service you turned on gets the current step (never your screen or voice)",
  yourTurn: "Your turn",
  stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
  openHode: (goal: string) => `Hode · ${goal}`,
  clarify: "I'm not confident which control you need. Move your pointer near the area you're working in.",
  /** Said the moment the learner asks something, so there's no dead air while Hodey looks. */
  acks: ["Let me look.", "One sec.", "Sure, let me see.", "Okay, looking now."],
  youAsked: (question: string) => `You: “${question}”`,
  helpStandingBy: "I'm here if you get stuck. Ask me anytime.",
  allSteps: "All steps",
  modeLabel: "Mode",
  agentStyleLabel: "Agent",
  continue: "Continue",
  takeOver: "I'll take over",
  acting: (label: string, right: boolean) => `${right ? "Right-clicking" : "Clicking"} ${label}…`,
  actingDetail: "Hodey is doing this step. Pause or take over before it clicks if something looks wrong.",
  checkpointTitle: "Check Hodey's work",
  checkpointDetail: (objective: string) => `Just done: ${objective}. Continue when it looks right.`,
  hodeyDidIt: "Hodey did the clicking. Check the result.",
  switchToApp: (app: string) => `Open ${app}, or switch to it, and I'll pick up there.`,
  connectPhone: "Connect your iPhone: open Show iPhone in Hodey's menu and start mirroring. I'll pick up there.",
  clarifyPhone: "I can't spot that on your iPhone yet. Scroll a little and I'll look again.",
  needVisionToAnswer: "I can only answer that with the local vision model, which isn't ready. Try pointing at the spot with Point & Ask.",
  itsHere: (name: string) => `That's ${name}. I've highlighted it.`,
  noPack: "I don't have a Hode for that yet. Try “make a pivot table” or “zip these files”.",
  hodeCompleteSpeech: "Hode complete. Nice work.",
  rememberedOnYourOwn: "Got it — you remembered that on your own.",
  fallbackNotice: "Switched to the local planner.",
  focusSet: "Focus set. Start a Hode and I'll look there first.",
  nothingMarked: "I can't make out a control there yet. Try marking a smaller area around one button.",
  position: "Position",
  dockTop: "Top",
  dockLeft: "Left",
  dockRight: "Right",
  whenIdle: "When idle",
  sidebarStyle: "Sidebar",
  sidebarCopilot: "Copilot",
  sidebarFloating: "Floating",
  sidebarCopilotTip: "Copilot moves your windows aside so Hodey never covers them.",
  alwaysShow: "Always show",
  autoHide: "Auto-hide",
  hideHodey: "Hide Hodey",
  showIphone: "Show iPhone",
  hideIphone: "Hide iPhone",
  phoneSourceCamera: "USB cable",
  phoneSourceAirplay: "Wi-Fi (AirPlay)",
  phoneConnecting: "Connecting to your iPhone…",
  phoneWaitingAirplay: "On your iPhone: Control Center → Screen Mirroring → Hodeum.",
  phoneJoinHotspot: (ssid: string, passphrase: string) => `On your iPhone, join the Wi-Fi “${ssid}” (password ${passphrase}).`,
  phoneUsbLinked: "Your iPhone is connected by cable and sharing its hotspot.",
  phoneSameWifi: "Put your iPhone on the same Wi-Fi as this laptop.",
  phoneMirrorToHodeum: "Open Control Center → Screen Mirroring → Hodeum.",
  phoneUsbTip: "Or connect the USB-C cable, turn on Personal Hotspot on the iPhone, and press Try again.",
  phoneUseWifi: "iPhone already on this laptop's Wi-Fi? Use that",
  phoneUseDirect: "Use the cable or this laptop's hotspot",
  phoneWaitingCamera: "Plug in your iPhone, start iPhoneMirror, then unlock the phone.",
  phoneSetupHint: "Setup guide: docs/iphone-mirroring.md",
  closeIphone: "Close iPhone view",
  phoneCamera: "Video input",
  phoneSource: "iPhone source",
  bringsBack: "brings it back",
  dragTip: "You can also drag Hodey by its face to the top or either side.",
  hodeySettings: "Hodey settings",
  micMenu: "Microphone and speech model",
  speakerMenu: "Speaker and voice",
  microphone: "Microphone",
  speechModel: "Speech model",
  speaker: "Speaker",
  hodeyVoice: "Hodey's voice",
  voiceDefault: "Hodey's default",
  voiceMenuLoading: "Finding your microphones and speakers…",
  voiceMenuFailed: "Couldn't list your audio devices",
  steps: "Steps",
  yourSkills: "Your skills",
  back: "Back",
  nextUp: "Next up",
  skillsLoading: "Loading your skills…",
  skillsFailed: "Couldn't load your skills",
  skillsHint: "Each Hode adds to this map. Linked skills build on the one before.",
  visionReady: "Local vision ready",
  visionStarting: "Local vision is loading…",
  visionMissing: "Local vision isn't installed. Run scripts/setup-local-ai.ps1.",
  visionFailed: "Local vision stopped",
  repeat: "Say that again",
  lookAgain: "Look again",
  skipStep: "Skip step",
  practiceAlone: "Practice on your own",
  quickCheck: "Quick check",
  openApp: "Open Hodeum",
  backToNotch: "Back to notch",
  mic: "Talk to Hodey",
  micStop: "Stop listening",
  listening: "Hodey is listening…",
  naturalVoiceMissing: "Hodey's natural voice isn't installed, so it's using the Windows voice. Run scripts/setup-local-ai.ps1 to add it.",
  voiceNotInstalled: "Voice input needs local speech recognition, which isn't installed yet.",
  stop: "Stop",
  webEyebrow: "Ask Hodey · Web search",
  searchingWeb: (query: string) => `Searching the web for “${query}”…`,
  webOnlyQuery: "Only this search leaves your PC.",
  webFound: (sites: number) => `Found results on ${sites} ${sites === 1 ? "site" : "sites"}. Hodey is answering in the app.`,
  readingWeb: (hosts: string) => `Reading what I found on ${hosts}…`,
  webNothing: "Found nothing relevant on the web. Answering from what I know.",
  webFallback: "Couldn't reach the web. Answering from what I know.",
  offlineHelp: (title: string) => `Using Hodey's offline help: ${title}…`,
  webNothingBecause: (reasons: string) => `Found nothing relevant on the web (${reasons}). Answering from what I know.`,
  webDecideFailed: (why: string) => `Hodey couldn't work out what to search for: ${why}`,
  webFromMemory: (hosts: string) => `Using what I found earlier on ${hosts}…`,
  privacyScreen: "Hodey is reading your screen",
  privacyMic: "Microphone is on",
  privacyCloud: "A cloud service is receiving data",
  progressNotSaved: "Progress won't be saved this session — the local database didn't open.",
} as const;
