/** Every learner-facing string. Product vocabulary follows CLAUDE.md. */
export const COPY = {
  idleTitle: "Hodey",
  startHode: "Start a Hode",
  begin: "Begin",
  askHodey: "Ask Hodey",
  looking: "Hodey is looking at this screen…",
  needHint: "Need a hint?",
  hint: "Hint",
  explain: "Explain",
  letMeTry: "Let me try",
  pointAndAsk: "Point & Ask",
  pause: "Pause",
  resume: "Resume",
  end: "End Hode",
  retry: "Try again",
  gotIt: "Got it",
  cancel: "Cancel",
  mute: "Mute voice",
  unmute: "Unmute voice",
  paused: "Paused",
  hodeComplete: "Hode complete",
  skillLearned: "Skill learned ✓",
  goalPrompt: "What do you want to learn?",
  goalPlaceholder: "e.g. make a pivot table in Excel",
  annotateTitle: "Mark the spot, then ask",
  annotateDetail: "Drag a box · Shift-draw to circle · Esc to cancel",
  composerPlaceholder: "Ask about this area…",
  composerHint: "Enter to ask · Esc to cancel",
  whatIsThis: "What is this?",
  howDoIUse: "How do I use this?",
  focusHere: "Focus here",
  somethingWrong: "Hodey hit a problem",
  local: "Local",
  enhanced: "Enhanced",
  localTitle: "Everything runs on this PC",
  enhancedTitle: "A cloud service you turned on gets the current step (never your screen or voice)",
  yourTurn: "Your turn",
  stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
  openHode: (goal: string) => `Hode · ${goal}`,
  clarify: "I'm not confident which control you need. Move your pointer near the area you're working in.",
  /** Said the moment the learner asks something, so there's no dead air while Hodey looks. */
  acks: ["Let me look.", "One sec.", "Sure, let me see.", "Okay, looking now."],
  youAsked: (question: string) => `You: “${question}”`,
  helpStandingBy: "I'm here if you get stuck. Ask me anytime.",
  allSteps: "All steps",
  modeLabel: "Mode",
  switchToApp: (app: string) => `Open ${app}, or switch to it, and I'll pick up there.`,
  connectPhone: "Connect your iPhone: open Show iPhone in Hodey's menu and start mirroring. I'll pick up there.",
  clarifyPhone: "I can't spot that on your iPhone yet. Scroll a little and I'll look again.",
  needVisionToAnswer: "I can only answer that with the local vision model, which isn't ready. Try pointing at the spot with Point & Ask.",
  itsHere: (name: string) => `That's ${name}. I've highlighted it.`,
  noPack: "I don't have a Hode for that yet. Try “make a pivot table” or “zip these files”.",
  hodeCompleteSpeech: "Hode complete. Nice work.",
  rememberedOnYourOwn: "Got it — you remembered that on your own.",
  fallbackNotice: "Switched to the local planner.",
  focusSet: "Focus set. Start a Hode and I'll look there first.",
  nothingMarked: "I can't make out a control there yet. Try marking a smaller area around one button.",
  position: "Position",
  dockTop: "Top",
  dockLeft: "Left",
  dockRight: "Right",
  whenIdle: "When idle",
  sidebarStyle: "Sidebar",
  sidebarCopilot: "Copilot",
  sidebarFloating: "Floating",
  sidebarCopilotTip: "Copilot moves your windows aside so Hodey never covers them.",
  alwaysShow: "Always show",
  autoHide: "Auto-hide",
  hideHodey: "Hide Hodey",
  showIphone: "Show iPhone",
  hideIphone: "Hide iPhone",
  phoneSourceCamera: "Cable / camera",
  phoneSourceAirplay: "AirPlay",
  phoneConnecting: "Connecting to your iPhone…",
  phoneWaitingAirplay: "On your iPhone: Control Center → Screen Mirroring → Hodeum.",
  phoneWaitingCamera: "Start iPhoneMirror and unlock your iPhone.",
  phoneSetupHint: "Setup guide: docs/iphone-mirroring.md",
  closeIphone: "Close iPhone view",
  phoneCamera: "Camera",
  phoneSource: "iPhone source",
  bringsBack: "brings it back",
  dragTip: "You can also drag Hodey by its face to the top or either side.",
  hodeySettings: "Hodey settings",
  steps: "Steps",
  yourSkills: "Your skills",
  back: "Back",
  nextUp: "Next up",
  skillsLoading: "Loading your skills…",
  skillsFailed: "Couldn't load your skills",
  skillsHint: "Each Hode adds to this map. Linked skills build on the one before.",
  visionReady: "Local vision ready",
  visionStarting: "Local vision is loading…",
  visionMissing: "Local vision isn't installed. Run scripts/setup-local-ai.ps1.",
  visionFailed: "Local vision stopped",
  repeat: "Say that again",
  lookAgain: "Look again",
  openApp: "Open Hodeum",
  backToNotch: "Back to notch",
  mic: "Talk to Hodey",
  micStop: "Stop listening",
  listening: "Hodey is listening…",
  naturalVoiceMissing: "Hodey's natural voice isn't installed, so it's using the Windows voice. Run scripts/setup-local-ai.ps1 to add it.",
  voiceNotInstalled: "Voice input needs local speech recognition, which isn't installed yet.",
  privacyScreen: "Hodey is reading your screen",
  privacyMic: "Microphone is on",
  privacyCloud: "A cloud service is receiving data",
  progressNotSaved: "Progress won't be saved this session — the local database didn't open.",
} as const;
