/** Every learner-facing string. Product vocabulary follows CLAUDE.md. */
export const COPY = {
  idleTitle: "Hodey",
  startHode: "Start a Hode",
  begin: "Begin",
  askHodey: "Ask Hodey",
  looking: "Hodey is looking at this screen…",
  needHint: "Need a hint?",
  hint: "Hint",
  explain: "Explain",
  letMeTry: "Let me try",
  pointAndAsk: "Point & Ask",
  pause: "Pause",
  resume: "Resume",
  end: "End Hode",
  retry: "Try again",
  gotIt: "Got it",
  cancel: "Cancel",
  mute: "Mute voice",
  unmute: "Unmute voice",
  paused: "Paused",
  hodeComplete: "Hode complete",
  skillLearned: "Skill learned ✓",
  goalPrompt: "What do you want to learn?",
  goalPlaceholder: "e.g. make a pivot table in Excel",
  annotateTitle: "Mark the spot, then ask",
  annotateDetail: "Drag a box · Shift-draw to circle · Esc to cancel",
  composerPlaceholder: "Ask about this area…",
  composerHint: "Enter to ask · Esc to cancel",
  whatIsThis: "What is this?",
  howDoIUse: "How do I use this?",
  focusHere: "Focus here",
  somethingWrong: "Hodey hit a problem",
  local: "Local",
  yourTurn: "Your turn",
  stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
  openHode: (goal: string) => `Hode · ${goal}`,
  clarify: "I'm not confident which control you need. Move your pointer near the area you're working in.",
  switchToApp: (app: string) => `Open ${app}, or switch to it, and I'll pick up there.`,
  noPack: "I don't have a Hode for that yet. Try “make a pivot table” or “zip these files”.",
  hodeCompleteSpeech: "Hode complete. Nice work.",
  rememberedOnYourOwn: "Got it — you remembered that on your own.",
  fallbackNotice: "Switched to the local planner.",
  focusSet: "Focus set. Start a Hode and I'll look there first.",
  nothingMarked: "I can't make out a control there yet. Try marking a smaller area around one button.",
  position: "Position",
  dockTop: "Top",
  dockLeft: "Left",
  dockRight: "Right",
  whenIdle: "When idle",
  sidebarStyle: "Sidebar",
  sidebarCopilot: "Copilot",
  sidebarFloating: "Floating",
  sidebarCopilotTip: "Copilot moves your windows aside so Hodey never covers them.",
  alwaysShow: "Always show",
  autoHide: "Auto-hide",
  hideHodey: "Hide Hodey",
  bringsBack: "brings it back",
  dragTip: "You can also drag Hodey by its face to the top or either side.",
  hodeySettings: "Hodey settings",
  steps: "Steps",
  visionReady: "Local vision ready",
  visionStarting: "Local vision is loading…",
  visionMissing: "Local vision isn't installed. Run scripts/setup-local-ai.ps1.",
  visionFailed: "Local vision stopped",
  repeat: "Say that again",
  lookAgain: "Look again",
  openApp: "Open Hodeum",
  mic: "Talk to Hodey",
  micStop: "Stop listening",
  voiceNotInstalled: "Voice input needs local speech recognition, which isn't installed yet.",
  privacyScreen: "Hodey is reading your screen",
  privacyMic: "Microphone is on",
  privacyCloud: "A cloud service is receiving data",
  progressNotSaved: "Progress won't be saved this session — the local database didn't open.",
} as const;
